### ISSUE TITLE
submits empty entities list?

### ISSUE THREAD

**Issue by 33mhz** [dg01d/KnownPnut#1]
I haven't looked at the source yet, but when you cross-post, the pnut API isn't parsing links out of the post. If the post is sending a list of links, that's probably why. Excluding the list completely will let the server parse it, or it may be included wrongly or something. Something to look at. :)

**Comment by dg01d** [comment]
Yeah, it is doing that, it appears to be iterating through the message and extracting all entities, usernames, hashtags &c, and returning those as separate entity classes.

**Comment by 33mhz** [comment]
Took a look. Definitely safe to remove `getEntities()`. 👍

**Comment by dg01d** [comment]
This appears to be fixed. Removing all processing of URLs in my script resulted in pnut rendering them perfectly.
